### ISSUE TITLE
[ComputerCraft-Coroutine-0/WARN]

### ISSUE THREAD

**Issue by MrLoLf** [cc-tweaked/CC-Tweaked#1066] opened 2022-04-10 08:50 UTC
Forge 40.0.41
cc-tweaked-1.18.2-1.100.4
modpack [ATM7](https://github.com/AllTheMods/ATM-7/)

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/8458592/latest.log)

Throwing Warnings from line 1047-1078 that a lot of methods with biggerreactors should be final 
Using this [program](https://pastebin.com/YnZf1HAR) to control my reactor with cc, which calls [this](https://pastebin.com/NY6MU58s) program.

**Comment by SquidDev** [comment] 2022-04-10 13:24
This is caused by BiggerReactor's integration with CC, not CC itself. Really their peripheral methods should be marked as final, but it's not the end of the world if they're not.

**Closed by SquidDev** 2022-04-10 13:24 UTC
Labels: bug, invalid, area-Minecraft
