### ISSUE TITLE
Server crashed upon calling `commands.getBlockInfo`

### ISSUE THREAD

**Issue by Cheatoid** [cc-tweaked/CC-Tweaked#1040] opened 2022-02-13 21:06 UTC
### Minecraft Version

1.18.1

### Version

1.100.2

### Forge Version

39.0.75

## Steps to reproduce
Assuming Command computer is enabled and can be used.
1. Place a Command computer anywhere (I have placed it near spawn in overworld dimension).
2. Access Command computer's terminal.
    1. Enter `lua` to open Lua interactive shell.
    2. Copy/paste/run the following piece of code:
        `commands.getBlockInfo(commands.getBlockPosition())`

As soon as you run that command, the server will crash/close and therefore all players will also be kicked from the server. Also tested in singleplayer, crashed as well.

<details><summary>Server log (click to expand)</summary>

Seems like exception in server tick loop...

<pre>
[Server thread/ERROR]: Exception caught during firing event: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.BlockEntity.save(net.minecraft.nbt.CompoundTag)'
        Index: 3
        Listeners:
                0: NORMAL
                1: ASM: class dan200.computercraft.shared.peripheral.monitor.MonitorWatcher onTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                2: ASM: class dan200.computercraft.shared.util.TickScheduler tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                3: ASM: class dan200.computercraft.shared.CommonHooks onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                4: ASM: net.minecraftforge.common.ForgeInternalHandler@3f642d62 onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.BlockEntity.save(net.minecraft.nbt.CompoundTag)'
        at TRANSFORMER/computercraft@1.100.2/dan200.computercraft.shared.computer.apis.CommandAPI.getBlockInfo(CommandAPI.java:84)
        at TRANSFORMER/computercraft@1.100.2/dan200.computercraft.shared.computer.apis.CommandAPI.getBlockInfo(CommandAPI.java:268)
        at dan200.computercraft.shared.computer.apis.CommandAPI$cc$getBlockInfo112.apply(CC generated method)
        at TRANSFORMER/computercraft@1.100.2/dan200.computercraft.core.asm.LuaMethod.lambda$static$0(LuaMethod.java:16)
        at TRANSFORMER/computercraft@1.100.2/dan200.computercraft.core.lua.LuaContext.lambda$issueMainThreadTask$0(LuaContext.java:34)
        at TRANSFORMER/computercraft@1.100.2/dan200.computercraft.core.computer.MainThreadExecutor.execute(MainThreadExecutor.java:143)
        at TRANSFORMER/computercraft@1.100.2/dan200.computercraft.core.computer.MainThread.executePendingTasks(MainThread.java:157)
        at TRANSFORMER/computercraft@1.100.2/dan200.computercraft.shared.CommonHooks.onServerTick(CommonHooks.java:60)
        at net.minecraftforge.eventbus.ASMEventHandler_23_CommonHooks_onServerTick_ServerTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@39.0.75/net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:881)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
        at java.base/java.lang.Thread.run(Thread.java:833)

[Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.BlockEntity.save(net.minecraft.nbt.CompoundTag)'
        at dan200.computercraft.shared.computer.apis.CommandAPI.getBlockInfo(CommandAPI.java:84) ~[cc-tweaked-1.18.1-1.100.2.jar%2337!/:1.100.2]
        at dan200.computercraft.shared.computer.apis.CommandAPI.getBlockInfo(CommandAPI.java:268) ~[cc-tweaked-1.18.1-1.100.2.jar%2337!/:1.100.2]
        at dan200.computercraft.shared.computer.apis.CommandAPI$cc$getBlockInfo112.apply(CC generated method) ~[?:?]
        at dan200.computercraft.core.asm.LuaMethod.lambda$static$0(LuaMethod.java:16) ~[cc-tweaked-1.18.1-1.100.2.jar%2337!/:1.100.2]
        at dan200.computercraft.core.lua.LuaContext.lambda$issueMainThreadTask$0(LuaContext.java:34) ~[cc-tweaked-1.18.1-1.100.2.jar%2337!/:1.100.2]
        at dan200.computercraft.core.computer.MainThreadExecutor.execute(MainThreadExecutor.java:143) ~[cc-tweaked-1.18.1-1.100.2.jar%2337!/:1.100.2]
        at dan200.computercraft.core.computer.MainThread.executePendingTasks(MainThread.java:157) ~[cc-tweaked-1.18.1-1.100.2.jar%2337!/:1.100.2]
        at dan200.computercraft.shared.CommonHooks.onServerTick(CommonHooks.java:60) ~[cc-tweaked-1.18.1-1.100.2.jar%2337!/:1.100.2]
        at net.minecraftforge.eventbus.ASMEventHandler_23_CommonHooks_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:881) ~[forge-1.18.1-39.0.75-universal.jar%2343!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.18.1-20211210.034407-srg.jar%2339!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2339!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2339!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
</pre>

</details>

**Comment by Cheatoid** [comment] 2022-02-13 23:08
Temporarily fixed by downgrading Forge to version 39.0.0 (on client and server), so the above code does not crash the server for now.
Forge 1.18 is still in beta `¯¯\_(ツ)_/¯¯`

**Comment by SquidDev** [comment] 2022-02-14 11:59
Probably caused by https://github.com/MinecraftForge/MinecraftForge/commit/75408c1a705dd51a5879b2612df310389bfe0143. 39.0.44 or before should be safe to use, though we should probably fix this.

**Comment by SquidDev** [comment] 2022-03-03 10:43
Fixed in 6735cfd12e12534309b531944599584ef8f509da.

**Closed by SquidDev** 2022-03-03 10:43 UTC
Labels: bug, area-Minecraft
