### ISSUE TITLE
Shader Causes crash when rendering cc tweaked items

### ISSUE THREAD

**Issue by WelpSTudent** [cc-tweaked/CC-Tweaked#1005] opened 2021-12-30 23:59 UTC
### Minecraft Version

1.18.x

### Version

1.100.0

### Details

![image](https://user-images.githubusercontent.com/63996164/147795243-744f6329-f686-4327-8e8a-ec0697c243e6.png)
https://pastebin.com/S8L62K69
Crash happening from shaders and cc tweaked

**Comment by SquidDev** [comment] 2021-12-31 05:00
Duplicate of #989. This is an optifine problem.

**Closed by SquidDev** 2021-12-31 05:00 UTC
Labels: bug
