### ISSUE TITLE
Modloading error on latest forge 4.0.18+

### ISSUE THREAD

**Issue by Lothrazar** [cc-tweaked/CC-Tweaked#1050] opened 2022-03-20 15:09 UTC
### Minecraft Version

1.18.x

### Version

cc-tweaked-1.18.2-1.100.3

### Details

Forge api change with the latest version

instead of something like 
DeferredRegister.create(ForgeRegistries.LOOT_MODIFIER_SERIALIZERS, Const.MODID);
It will be a different import 
`DeferredRegister.create(ForgeRegistries.Keys.LOOT_MODIFIER_SERIALIZERS, Const.MODID);`

error log is this, with newest forge . 4.0.19 is out now

```
[08:00:17] [modloading-worker-0/ERROR]: Failed to register automatic subscribers. ModID: computercraft, class dan200.computercraft.ComputerCraft
java.lang.NoClassDefFoundError: net/minecraftforge/event/RegistryEvent$NewRegistry
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?]
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[javafmllanguage-1.18.2-40.0.19.jar%23154!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.18.2-40.0.19.jar%23154!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.18.2-40.0.19.jar%23154!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.19.jar%23153!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.RegistryEvent$NewRegistry
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 18 more```

**Comment by Wojbie** [comment] 2022-03-20 15:15
Duplicate of  #1049

**Closed** 2022-03-20 16:37 UTC
Labels: bug
