### ISSUE TITLE
Crash when rendering Advanced Turtle.

### ISSUE THREAD

**Issue by Canada-LaVearn** [cc-tweaked/CC-Tweaked#1013] opened 2022-01-08 22:01 UTC
### Minecraft Version

1.18.x

### Version

1.100.1

### Details

[crash-2022-01-08_15.53.01-client.txt](https://github.com/cc-tweaked/CC-Tweaked/files/7834087/crash-2022-01-08_15.53.01-client.txt)

Reading the log, it appears that the crash was caused by attempting to render an advanced turtle.

This issue crashed a user's client while playing on my server, The server did not crash.

**Comment by SquidDev** [comment] 2022-01-09 00:35
Duplicate of #989. This is an optifine problem.

**Closed by SquidDev** 2022-01-09 00:35 UTC
Labels: bug
