### ISSUE TITLE
Disk recipes broken

### ISSUE THREAD

**Issue by Sunekaer** [cc-tweaked/CC-Tweaked#652] opened 2021-01-04 19:22 UTC
Red+paper gives blue disk.
Adding dye in the crafting gives no result.
JEI shows 16 recipes for white disk and none of the recipes works.

![image](https://user-images.githubusercontent.com/18720460/103570830-13f33b80-4eca-11eb-9222-9b705bc6b63e.png)

## Useful information to include:
 - Minecraft version: forge 1.16.4 35.1.15 
 - CC: Tweaked version: cc-tweaked-1.16.4-1.95.0.jar
 - jei-1.16.4-7.6.1.65.jar
 - Logs: No error in logs

**Comment by Sunekaer** [comment] 2021-01-09 11:16
Still broken
![image](https://user-images.githubusercontent.com/18720460/104090064-4909e000-5274-11eb-90c0-0e90cd91a1c2.png)
![image](https://user-images.githubusercontent.com/18720460/104090066-4c04d080-5274-11eb-9a72-0817b1382b8f.png)
![image](https://user-images.githubusercontent.com/18720460/104090067-4f985780-5274-11eb-8961-86580d8e0b72.png)
![image](https://user-images.githubusercontent.com/18720460/104090071-545d0b80-5274-11eb-8fe6-578548a483c8.png)
![image](https://user-images.githubusercontent.com/18720460/104090073-5757fc00-5274-11eb-9bb0-891989e3aa9f.png)

And in JEI They still all show as all the recipes makes white disk

**Comment by Lupus590** [comment] 2021-01-09 11:26
I can't see the recipe in JEI on my single-player mod pack.

The craft works though.

**Comment by SquidDev** [comment] 2021-01-09 18:37
I've just pushed a fix for the JEI recipes. Sorry, entirely forgot to fix that last time.

I'm afraid I can't reproduce the issues you're seeing with crafting though. It's very odd that red dye is crafting both blue and red disks - the order shouldn't matter at all. Does this happen with just CC:T, or with the whole modpack?

Probably worth mentioning that getting a "blue" disk when no dye is provided is expected behaviour. Dates back to very old ComputerCraft when disks weren't dyeable.

**Comment by Sunekaer** [comment] 2021-01-13 15:30
Okay so i did the recipe mod i have from touching recipes of type `'computercraft:impostor_shapeless'`
now there is this issue: https://s1.sunekaer.com/i/13-01-2021_16-29-08_%25pn.gif

**Comment by SquidDev** [comment] 2021-01-13 15:53
@Sunekaer Just curious what recipe mod you're using that might be causing conflicts? I couldn't see anything obvious in the DW20 pack.

**Comment by Sunekaer** [comment] 2021-01-13 16:07
KubeJS

**Closed** 2022-07-02 16:15 UTC
Labels: bug, area-Minecraft
